def solve_math(text, context=None):
    """
    Prepare a mathematics request for the final LLM.

    The actual mathematical solution is generated by
    the final LLM, so this skill does not make an
    additional Gemini/API request.
    """

    if not text:
        return ""

    text = str(text).strip()

    if not text:
        return ""

    math_context = f"""
========== MATH REQUEST ==========

Solve the following mathematical problem
carefully and show the necessary steps.

Check the calculation before giving the
final answer.

Problem:
{text}

==================================
"""

    return math_context.strip()